#!/usr/bin/env python3
"""
Second Brain - Knowledge Management System
"""

import os
import json
from datetime import datetime
from pathlib import Path

# Configuration
BRAIN_DIR = Path("/root/.openclaw/workspace/memory/second-brain")
FOLDERS = ["inbox", "daily", "projects", "areas", "resources", "archives", "insights"]

def ensure_structure():
    """Ensure second brain folder structure exists."""
    BRAIN_DIR.mkdir(parents=True, exist_ok=True)
    for folder in FOLDERS:
        (BRAIN_DIR / folder).mkdir(exist_ok=True)

def capture(content, source="user"):
    """Capture a thought/idea to inbox."""
    ensure_structure()
    
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"{timestamp}_{source}.md"
    filepath = BRAIN_DIR / "inbox" / filename
    
    note = f"""# Capture - {datetime.now().strftime("%Y-%m-%d %H:%M")}

**Source:** {source}

{content}

---
*Captured by Second Brain*
"""
    
    with open(filepath, 'w') as f:
        f.write(note)
    
    return f"✅ Captured to inbox/{filename}"

def search(query):
    """Search through all notes."""
    results = []
    
    for folder in FOLDERS:
        folder_path = BRAIN_DIR / folder
        if folder_path.exists():
            for file in folder_path.glob("*.md"):
                with open(file, 'r') as f:
                    content = f.read()
                    if query.lower() in content.lower():
                        results.append({
                            "file": file.name,
                            "folder": folder,
                            "preview": content[:200] + "..."
                        })
    
    return results

def get_daily_note():
    """Get or create today's daily note."""
    ensure_structure()
    
    today = datetime.now().strftime("%Y-%m-%d")
    filename = f"{today}.md"
    filepath = BRAIN_DIR / "daily" / filename
    
    if not filepath.exists():
        with open(filepath, 'w') as f:
            f.write(f"""# Daily Notes - {today}

## Morning Thoughts

## Ideas & Insights

## Links & References

## Evening Reflection

---
*Daily note by Second Brain*
""")
    
    return filepath

def generate_insights():
    """Generate AI insights from recent notes."""
    ensure_structure()
    
    # Collect recent notes (last 7 days)
    recent_notes = []
    for folder in ["inbox", "daily"]:
        folder_path = BRAIN_DIR / folder
        if folder_path.exists():
            for file in folder_path.glob("*.md"):
                try:
                    # Check if file is recent (simplified check)
                    with open(file, 'r') as f:
                        recent_notes.append(f"File: {file.name}\n{f.read()[:500]}")
                except:
                    pass
    
    insight_file = BRAIN_DIR / "insights" / f"insights_{datetime.now().strftime('%Y%m%d')}.md"
    
    with open(insight_file, 'w') as f:
        f.write(f"""# AI Insights - {datetime.now().strftime("%Y-%m-%d")}

## Recent Activity Summary

*Based on {len(recent_notes)} recent notes*

### Key Themes

- Theme 1: [Detected from notes]
- Theme 2: [Detected from notes]

### Patterns Observed

- Pattern 1
- Pattern 2

### Suggested Connections

- Connection between [Note A] and [Note B]
- Potential link to [Previous Project]

### Action Items

- [ ] Review and organize inbox
- [ ] Follow up on [topic]
- [ ] Connect [idea A] with [idea B]

---
*Generated by Second Brain AI*
""")
    
    return str(insight_file)

if __name__ == "__main__":
    import sys
    
    if len(sys.argv) < 2:
        print("Usage: python second_brain.py [capture|search|daily|insights] [args...]")
        sys.exit(1)
    
    command = sys.argv[1]
    
    if command == "capture" and len(sys.argv) > 2:
        content = " ".join(sys.argv[2:])
        print(capture(content))
    
    elif command == "search" and len(sys.argv) > 2:
        query = " ".join(sys.argv[2:])
        results = search(query)
        for r in results:
            print(f"\n📁 {r['folder']}/{r['file']}")
            print(r['preview'][:100] + "...")
    
    elif command == "daily":
        daily = get_daily_note()
        print(f"📅 Daily note: {daily}")
    
    elif command == "insights":
        insight = generate_insights()
        print(f"🧠 Insights generated: {insight}")
    
    else:
        print("Unknown command")
